dist: trusty
sudo: true
language: node_js
branches:
  only:
  - develop
git:
  submodules: false
node_js:
- 10.22.0
before_install:
- npm update -g npm
install:
- npm install
after_success:
  - pip install --user codecov
  - codecov --file coverage/lcov.info --disable search

